apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: java-app
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 5m0s
  path: ./apps/java-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
